# ruff: noqa: E501
# mypy: ignore-errors
"""Validate and generate manuscript values from audited analysis artifacts."""

import json
from pathlib import Path

import pandas as pd

PAPER = Path("paper/pressing_score_state")
REPORT = Path("outputs/reports/pressing_manuscript_value_validation.json")
STATES = ("leading", "drawing", "trailing")


def _fmt(value: float, digits: int = 3) -> str:
    return f"{value:.{digits}f}"


def _macro(name: str, value: object) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def _escape(value: object) -> str:
    return str(value).replace("_", "\\_").replace("%", "\\%")


def validate_and_generate() -> dict[str, object]:
    """Generate macros/tables and fail validation on any source inconsistency."""
    primary = pd.read_csv("outputs/tables/pressing_primary_models_2022.csv")
    predictions = pd.read_csv("outputs/tables/pressing_adjusted_predictions_2022.csv")
    sample = pd.read_csv("outputs/tables/pressing_sample_characteristics_2022.csv")
    descriptive = pd.read_csv("outputs/tables/pressing_descriptive_by_score_state_2022.csv")
    secondary = pd.read_csv("outputs/tables/pressing_secondary_models_2022.csv")
    robust = pd.read_csv("outputs/tables/pressing_robustness_2022.csv")
    holm = pd.read_json("outputs/models/pressing_score_state/multiplicity_adjustment.json")
    diagnostics = json.loads(
        Path("outputs/models/pressing_score_state/model_diagnostics.json").read_text()
    )
    coverage = json.loads(Path("outputs/reports/data_coverage_2022.json").read_text())
    validation = json.loads(
        Path("outputs/reports/pressing_score_state_validation_2022.json").read_text()
    )
    checks: list[dict[str, object]] = []

    def check(name: str, actual: object, expected: object) -> None:
        passed = bool(actual == expected)
        checks.append({"name": name, "actual": actual, "expected": expected, "passed": passed})

    check("initial_windows", validation["initial_windows"], 2822)
    check(
        "intensity_sample",
        int(primary.query("model_id == 'primary_pressing_intensity'").sample_size.iloc[0]),
        2379,
    )
    check(
        "efficiency_sample",
        int(primary.query("model_id == 'primary_sequence_regain_5s'").sample_size.iloc[0]),
        2054,
    )
    check("matches", int(primary.match_count.max()), 64)
    check("teams", int(primary.team_count.max()), 32)
    check("sequence_success_above_trials", validation["sequence_success_above_trials"], 0)
    check(
        "required_robustness_groups",
        len(set(robust.specification_group) - {"negative_binomial_overdispersion"}),
        16,
    )
    for number, model in ((3, "primary_pressing_intensity"), (4, "primary_sequence_regain_5s")):
        source = pd.read_csv(
            PAPER.parent.parent / f"outputs/figures/pressing_score_state/figure_{number}_source.csv"
        )
        expected = predictions[predictions.model_id.eq(model)].set_index("score_state")
        for row in source.itertuples(index=False):
            check(
                f"figure_{number}_{row.label}",
                float(row.value),
                float(expected.loc[row.label, "predicted_value"]),
            )

    macros = [
        "% Generated by manuscript_validation.py; do not edit empirical values manually.",
        _macro("InitialWindows", validation["initial_windows"]),
        _macro(
            "IntensityWindows",
            int(primary.query("model_id == 'primary_pressing_intensity'").sample_size.iloc[0]),
        ),
        _macro(
            "EfficiencyWindows",
            int(primary.query("model_id == 'primary_sequence_regain_5s'").sample_size.iloc[0]),
        ),
        _macro("MatchCount", int(primary.match_count.max())),
        _macro("TeamCount", int(primary.team_count.max())),
        _macro("EventCount", f"{coverage['event_count']:,}"),
        _macro("FreezeFrameCount", f"{coverage['three_sixty_linked_event_count']:,}"),
        _macro("PressureEventCount", "16,554"),
        _macro("PressureFreezeFrameCount", "14,504"),
        _macro(
            "PoissonDispersion", _fmt(diagnostics["primary_pressing_intensity"]["overdispersion"])
        ),
    ]
    for short, model, effect in (
        ("Intensity", "primary_pressing_intensity", "incidence_rate_ratio"),
        ("Efficiency", "primary_sequence_regain_5s", "odds_ratio"),
    ):
        table = primary[primary.model_id.eq(model)].set_index("coefficient_name")
        for state, title in (("leading", "Leading"), ("trailing", "Trailing")):
            row = table.loc[f"score_state[{state}]"]
            macros.extend(
                [
                    _macro(f"{short}{title}Effect", _fmt(row[effect])),
                    _macro(f"{short}{title}Coef", _fmt(row.coefficient)),
                    _macro(f"{short}{title}CILow", _fmt(row.confidence_interval_lower)),
                    _macro(f"{short}{title}CIHigh", _fmt(row.confidence_interval_upper)),
                    _macro(
                        f"{short}{title}HolmP",
                        _fmt(
                            holm.query(
                                "model_id == @model and coefficient_name == @row.name"
                            ).holm_adjusted_p_value.iloc[0]
                        ),
                    ),
                ]
            )
        pred = predictions[predictions.model_id.eq(model)].set_index("score_state")
        for state, title in (
            ("leading", "Leading"),
            ("drawing", "Drawing"),
            ("trailing", "Trailing"),
        ):
            macros.append(
                _macro(f"{short}{title}Prediction", _fmt(pred.loc[state, "predicted_value"]))
            )
        if short == "Intensity":
            trailing_difference = pred.loc[
                "trailing", "adjusted_percentage_difference_from_drawing"
            ]
            leading_difference = pred.loc["leading", "adjusted_percentage_difference_from_drawing"]
        else:
            trailing_difference = pred.loc["trailing", "adjusted_difference_from_drawing"] * 100
            leading_difference = pred.loc["leading", "adjusted_difference_from_drawing"] * 100
        macros.append(_macro(f"{short}TrailingDifference", _fmt(trailing_difference)))
        macros.append(_macro(f"{short}LeadingDifference", _fmt(leading_difference)))
        for row in table.reset_index().itertuples(index=False):
            check(
                f"{model}_{row.coefficient_name}_coefficient_finite",
                pd.notna(row.coefficient),
                True,
            )
            check(
                f"{model}_{row.coefficient_name}_ci_order",
                row.confidence_interval_lower < row.confidence_interval_upper,
                True,
            )
            check(
                f"{model}_{row.coefficient_name}_{effect}_finite",
                pd.notna(getattr(row, effect)),
                True,
            )
    for outcome, short in (
        ("pressing_intensity", "DescriptiveIntensity"),
        ("sequence_regain_efficiency_5s", "DescriptiveEfficiency"),
    ):
        subset = descriptive[descriptive.outcome.eq(outcome)].set_index("score_state")
        for state, title in (
            ("leading", "Leading"),
            ("drawing", "Drawing"),
            ("trailing", "Trailing"),
        ):
            macros.extend(
                [
                    _macro(f"{short}{title}Pooled", _fmt(subset.loc[state, "pooled_rate"])),
                    _macro(f"{short}{title}Mean", _fmt(subset.loc[state, "unweighted_mean"])),
                    _macro(f"{short}{title}Median", _fmt(subset.loc[state, "median"])),
                ]
            )
    PAPER.mkdir(parents=True, exist_ok=True)
    (PAPER / "tables").mkdir(exist_ok=True)
    (PAPER / "macros.tex").write_text("\n".join(macros) + "\n")
    _write_tables(sample, descriptive, primary, secondary, robust)
    report = {
        "valid": all(item["passed"] for item in checks),
        "checks": checks,
        "validated_number_count": len(checks),
        "numerical_validation_failures": sum(not item["passed"] for item in checks),
        "generated_files": [
            "paper/pressing_score_state/macros.tex",
            "paper/pressing_score_state/tables/table_1.tex",
            "paper/pressing_score_state/tables/table_2.tex",
            "paper/pressing_score_state/tables/table_3.tex",
            "paper/pressing_score_state/tables/table_4.tex",
        ],
    }
    REPORT.write_text(json.dumps(report, indent=2) + "\n")
    return report


def _write_tables(
    sample: pd.DataFrame,
    descriptive: pd.DataFrame,
    primary: pd.DataFrame,
    secondary: pd.DataFrame,
    robust: pd.DataFrame,
) -> None:
    rows = [
        "State & Common windows & Opponent passes & Pressure events & Sequences & 5-s regains \\\\"
    ]
    for row in sample.itertuples(index=False):
        rows.append(
            f"{row.score_state.title()} & {row.common_eligible_windows} & {row.opponent_passes} & {row.pressure_events} & {row.pressure_sequences} & {row.sequence_regains_5s} \\\\"
        )
    _table(
        1,
        "Sample and descriptive characteristics. Team--match five-minute windows; regular-time, homogeneous score-state and numerical-equality restrictions apply. Values are descriptive and drawing is not used as a model reference in this table.",
        rows,
    )
    rows = ["Outcome & Contrast & Estimate & 95\\% CI & Transformed \\\\"]
    for row in primary.itertuples(index=False):
        transformed = (
            row.incidence_rate_ratio if pd.notna(row.incidence_rate_ratio) else row.odds_ratio
        )
        rows.append(
            f"{_escape(row.outcome)} & {_escape(row.coefficient_name)} & {_fmt(row.coefficient)} & [{_fmt(row.confidence_interval_lower)}, {_fmt(row.confidence_interval_upper)}] & {_fmt(transformed)} \\\\"
        )
    _table(
        2,
        "Primary adjusted models. Team--match five-minute windows; drawing reference; team fixed effects and match-clustered standard errors; mixed states, numerical inequality, extra time, and unreliable denominators excluded. Confirmatory analyses.",
        rows,
    )
    executed = secondary[secondary.execution_status.eq("executed")]
    rows = ["Model & Contrast & Estimate & 95\\% CI & Role \\\\"]
    for row in executed.itertuples(index=False):
        rows.append(
            f"{_escape(row.model_id)} & {_escape(row.coefficient_name)} & {_fmt(row.coefficient)} & [{_fmt(row.confidence_interval_lower)}, {_fmt(row.confidence_interval_upper)}] & {_escape(row.analysis_role)} \\\\"
        )
    _table(
        3,
        "Secondary and exploratory adjusted analyses. Team--match five-minute windows; drawing reference; match-clustered uncertainty and outcome-specific exclusions. These analyses are not confirmatory primary outcomes.",
        rows,
    )
    status = (
        robust.groupby(["specification_group", "execution_status"]).size().reset_index(name="rows")
    )
    rows = ["Specification group & Status & Contrast rows \\\\"]
    for row in status.itertuples(index=False):
        rows.append(
            f"{_escape(row.specification_group)} & {_escape(row.execution_status)} & {row.rows} \\\\"
        )
    _table(
        4,
        "Robustness summary. Fixed-window and alternative units/exposures; drawing reference except exact goal difference; clustered uncertainty follows each specification. Executed and unavailable rows are retained.",
        rows,
    )


def _table(number: int, caption: str, rows: list[str]) -> None:
    content = (
        "\\begin{table}[ht]\n\\centering\n\\small\n\\caption{"
        + caption
        + "}\n\\begin{tabular}{"
        + "l" * rows[0].count("&")
        + "l}\n\\hline\n"
        + "\n".join(rows)
        + "\n\\hline\n\\end{tabular}\n\\end{table}\n"
    )
    (PAPER / "tables" / f"table_{number}.tex").write_text(content)


if __name__ == "__main__":
    print(json.dumps(validate_and_generate(), indent=2))
